version: "3.8"

services:
  app:
    container_name: video_merger_app
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "6060:6060"
      - "4000:8000"
    restart: always
    volumes:
      - ./config:/app/config